modsecurity on;
modsecurity_rules '
  SecAuditEngine On
  SecAuditLog /var/log/modsecurity/audit.log
  SecAuditLogFormat JSON
  SecAuditLogParts ABCEFHJKZ
  SecAuditLogType Serial
  SecAuditLogRelevantStatus .*
';
